# Staging Environment Deployment Patch
# This patches the base deployment for staging-specific settings

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-web-app
  namespace: sample-app-staging
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: web-app
        env:
        - name: ENVIRONMENT
          value: "staging"
        - name: LOG_LEVEL
          value: "info"
        - name: FEATURE_FLAGS
          value: "staging"
        - name: DATABASE_URL
          value: "postgresql://staging-db:5432/sampleapp"
        - name: REDIS_URL
          value: "redis://staging-redis:6379"
        resources:
          requests:
            memory: "128Mi"
            cpu: "200m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
