# Velero Backup and Disaster Recovery Setup
# This installs and configures Velero for Kubernetes backup and restore

---
# Velero CRDs - Must be installed first
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: backups.velero.io
spec:
  group: velero.io
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              includedNamespaces:
                type: array
                items:
                  type: string
              excludedNamespaces:
                type: array
                items:
                  type: string
              includedResources:
                type: array
                items:
                  type: string
              excludedResources:
                type: array
                items:
                  type: string
              labelSelector:
                type: object
              snapshotVolumes:
                type: boolean
              storageLocation:
                type: string
              volumeSnapshotLocations:
                type: array
                items:
                  type: string
              ttl:
                type: string
          status:
            type: object
            properties:
              phase:
                type: string
              startTimestamp:
                type: string
                format: date-time
              completionTimestamp:
                type: string
                format: date-time
              version:
                type: integer
              progress:
                type: object
                properties:
                  itemsBackedUp:
                    type: integer
                  totalItems:
                    type: integer
  scope: Namespaced
  names:
    plural: backups
    singular: backup
    kind: Backup

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: backupstoragelocations.velero.io
spec:
  group: velero.io
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              provider:
                type: string
              objectStorage:
                type: object
                properties:
                  bucket:
                    type: string
                  prefix:
                    type: string
              config:
                type: object
                additionalProperties:
                  type: string
              credential:
                type: object
                properties:
                  name:
                    type: string
                  key:
                    type: string
          status:
            type: object
            properties:
              phase:
                type: string
              lastSyncedTime:
                type: string
                format: date-time
              lastSyncedRevision:
                type: string
  scope: Namespaced
  names:
    plural: backupstoragelocations
    singular: backupstoragelocation
    kind: BackupStorageLocation

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: volumesnapshotlocations.velero.io
spec:
  group: velero.io
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              provider:
                type: string
              config:
                type: object
                additionalProperties:
                  type: string
              credential:
                type: object
                properties:
                  name:
                    type: string
                  key:
                    type: string
          status:
            type: object
            properties:
              phase:
                type: string
              lastSyncedTime:
                type: string
                format: date-time
              lastSyncedRevision:
                type: string
  scope: Namespaced
  names:
    plural: volumesnapshotlocations
    singular: volumesnapshotlocation
    kind: VolumeSnapshotLocation

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: restores.velero.io
spec:
  group: velero.io
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              backupName:
                type: string
              includedNamespaces:
                type: array
                items:
                  type: string
              excludedNamespaces:
                type: array
                items:
                  type: string
              includedResources:
                type: array
                items:
                  type: string
              excludedResources:
                type: array
                items:
                  type: string
              labelSelector:
                type: object
              restorePVs:
                type: boolean
              storageLocation:
                type: string
              volumeSnapshotLocations:
                type: array
                items:
                  type: string
          status:
            type: object
            properties:
              phase:
                type: string
              startTimestamp:
                type: string
                format: date-time
              completionTimestamp:
                type: string
                format: date-time
              progress:
                type: object
                properties:
                  itemsRestored:
                    type: integer
                  totalItems:
                    type: integer
  scope: Namespaced
  names:
    plural: restores
    singular: restore
    kind: Restore

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: schedules.velero.io
spec:
  group: velero.io
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              schedule:
                type: string
              template:
                type: object
                properties:
                  includedNamespaces:
                    type: array
                    items:
                      type: string
                  excludedNamespaces:
                    type: array
                    items:
                      type: string
                  includedResources:
                    type: array
                    items:
                      type: string
                  excludedResources:
                    type: array
                    items:
                      type: string
                  labelSelector:
                    type: object
                  snapshotVolumes:
                    type: boolean
                  storageLocation:
                    type: string
                  volumeSnapshotLocations:
                    type: array
                    items:
                      type: string
                  ttl:
                    type: string
          status:
            type: object
            properties:
              phase:
                type: string
              lastBackup:
                type: string
                format: date-time
  scope: Namespaced
  names:
    plural: schedules
    singular: schedule
    kind: Schedule

---
# Cloud Credentials Secret (placeholder)
apiVersion: v1
kind: Secret
metadata:
  name: cloud-credentials
  namespace: velero
type: Opaque
data:
  cloud: YWJjZGVmZ2hpams=  # base64 encoded placeholder - replace with actual credentials

---
apiVersion: v1
kind: Namespace
metadata:
  name: velero
  labels:
    name: velero

---
# Velero Server Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: velero
  namespace: velero
  labels:
    component: velero
spec:
  replicas: 1
  selector:
    matchLabels:
      deploy: velero
  template:
    metadata:
      labels:
        deploy: velero
        component: velero
    spec:
      serviceAccountName: velero
      containers:
      - name: velero
        image: velero/velero:v1.11.1
        command:
        - /velero
        args:
        - server
        - --features=EnableCSI
        env:
        - name: VELERO_SCRATCH_DIR
          value: /scratch
        - name: VELERO_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: plugins
          mountPath: /plugins
        - name: scratch
          mountPath: /scratch
        - name: cloud-credentials
          mountPath: /credentials
          readOnly: true
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi
      volumes:
      - name: plugins
        emptyDir: {}
      - name: scratch
        emptyDir: {}
      - name: cloud-credentials
        secret:
          secretName: cloud-credentials

---
# Velero Service
apiVersion: v1
kind: Service
metadata:
  name: velero
  namespace: velero
  labels:
    component: velero
spec:
  ports:
  - port: 8085
    targetPort: 8085
    protocol: TCP
    name: metrics
  selector:
    deploy: velero

---
# Velero Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: velero
  namespace: velero

---
# Velero ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: velero
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - nodes
  - persistentvolumes
  - persistentvolumeclaims
  - pods
  - secrets
  - serviceaccounts
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  - statefulsets
  - daemonsets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - velero.io
  resources:
  - backups
  - backupstoragelocations
  - deletebackuprequests
  - downloadrequests
  - podvolumebackups
  - podvolumerestores
  - restores
  - schedules
  - serverstatusrequests
  - volumesnapshotlocations
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete

---
# Velero ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: velero
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: velero
subjects:
- kind: ServiceAccount
  name: velero
  namespace: velero

---
# Backup Storage Location (example for AWS S3)
apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: default
  namespace: velero
spec:
  provider: aws
  objectStorage:
    bucket: velero-backups
    prefix: devops-pipeline
  config:
    region: us-west-2
    s3ForcePathStyle: "false"
  credential:
    name: cloud-credentials
    key: cloud

---
# Volume Snapshot Location (example for AWS EBS)
apiVersion: velero.io/v1
kind: VolumeSnapshotLocation
metadata:
  name: default
  namespace: velero
spec:
  provider: aws
  config:
    region: us-west-2
  credential:
    name: cloud-credentials
    key: cloud
