# Blue-Green Deployment - Green Environment
# This represents the new version being deployed (Green)

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-web-app-green
  namespace: sample-app-prod
  labels:
    app: sample-web-app
    version: green
    environment: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-web-app
      version: green
  template:
    metadata:
      labels:
        app: sample-web-app
        version: green
        environment: production
    spec:
      containers:
      - name: web-app
        image: nginx:1.22-alpine  # New version
        ports:
        - containerPort: 80
          name: http
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: VERSION
          value: "green"
        - name: LOG_LEVEL
          value: "info"
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5

---
# Green Service - For testing before switching
apiVersion: v1
kind: Service
metadata:
  name: sample-web-app-green-service
  namespace: sample-app-prod
  labels:
    app: sample-web-app
    version: green
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: sample-web-app
    version: green
