# Production Environment Configuration
# This file configures the production environment using Kustomize

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sample-app-prod

resources:
- ../../applications/sample-app
- deployment-patch.yaml
- hpa.yaml
- pdb.yaml

commonLabels:
  environment: production
  tier: prod

patchesStrategicMerge:
- deployment-patch.yaml

images:
- name: nginx
  newTag: 1.21-alpine

replicas:
- name: sample-web-app
  count: 5

configMapGenerator:
- name: app-config
  literals:
  - ENVIRONMENT=production
  - LOG_LEVEL=warn
  - FEATURE_FLAGS=production
  - DATABASE_URL=postgresql://prod-db:5432/sampleapp
  - REDIS_URL=redis://prod-redis:6379

secretGenerator:
- name: app-secrets
  literals:
  - API_KEY=prod-api-key-789
  - JWT_SECRET=prod-jwt-secret-key
