# Development Environment Deployment Patch
# This patches the base deployment for development-specific settings

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-web-app
  namespace: sample-app-dev
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: web-app
        env:
        - name: ENVIRONMENT
          value: "development"
        - name: LOG_LEVEL
          value: "debug"
        - name: FEATURE_FLAGS
          value: "enabled"
        - name: DATABASE_URL
          value: "postgresql://dev-db:5432/sampleapp"
        - name: REDIS_URL
          value: "redis://dev-redis:6379"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
